name: Deploy to Nominalia via Webhook

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy Webhook
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: 📦 Archive website
      run: zip -r web_ocu.zip . -x "*.git*" ".github/*" "Backup*"
      
    - name: 🚀 Deploy to ocu.cat
      run: |
        curl -X POST --data-binary @web_ocu.zip "https://ocu.cat/github_deploy.php?token=${{ secrets.DEPLOY_TOKEN }}"
